- error: {lhs: inter newline, rhs: lined}
- error: {lhs: inter blankline, rhs: blanklined}
- error: {lhs: 'inter (string ", ")', rhs: hCommaSep}
- error: {lhs: 'prefixedLined ", "', rhs: vCommaSep}
- error: {lhs: 'inter (string " | ")', rhs: hBarSep}
- error: {lhs: 'prefixedLined "| "', rhs: vBarSep}
- error: {lhs: parens (hCommaSep x), rhs: hTuple x}
- error: {lhs: gets ((InsideDeclSig `elem`) . psInside), rhs: isInsideDeclSig}
- error: {lhs: gets ((InsideVerticalFunctionSignature `elem`) . psInside), rhs: isInsideVerticalFuncSig}
- error: {lhs: gets ((InsideInstDecl `elem`) . psInside), rhs: isInsideInstDecl}
- error: {lhs: gets ((InsideCase `elem`) . psInside), rhs: isInsideCase}
- error: {lhs: gets ((InsideVerticalList `elem`) . psInside), rhs: isInsideVerticalList}
