- error: {lhs: inter newline, rhs: lined}
- error: {lhs: 'inter (string ", ")', rhs: hCommaSep}
- error: {lhs: 'inter (string " | ")', rhs: barSeparated}
- error: {lhs: parens (hCommaSep x), rhs: hTuple x}
