- error: {lhs: inter newline, rhs: lined}
- error: {lhs: 'inter (string ", ")', rhs: hCommaSep}
- error: {lhs: 'prefixedLined ", "', rhs: vCommaSep}
- error: {lhs: 'inter (string " | ")', rhs: hBarSep}
- error: {lhs: 'prefixedLined "| "', rhs: vBarSep}
- error: {lhs: parens (hCommaSep x), rhs: hTuple x}
