{-# LANGUAGE CPP #-}

module HIndent.Ast.Literal
  ( Literal
  , mkLiteralFromHsLit
  , mkLiteralFromHsOverLit
  , mkLiteralFromHsTyLit
  ) where

import qualified Data.Text as Text
import qualified GHC.Data.FastString as GHC
import qualified GHC.Types.SourceText as GHC
import HIndent.Ast.TextValue
import qualified HIndent.GhcLibParserWrapper.GHC.Hs as GHC
import HIndent.Pretty
import HIndent.Pretty.Combinators
import Text.Show.Unicode

data Literal
  = Inline TextValue
  | MultilineString [TextValue]

instance Pretty Literal where
  pretty (Inline value) = pretty value
  pretty (MultilineString []) = pure ()
  pretty (MultilineString [value]) = pretty value
  pretty (MultilineString (value:values)) = do
    pretty value
    newline
    indentedWithFixedLevel 0 $ lined $ fmap pretty values

mkLiteralFromHsLit :: GHC.HsLit GHC.GhcPs -> Literal
mkLiteralFromHsLit x@(GHC.HsChar _ _) =
  Inline $ mkTextValueFromString $ showOutputable x
mkLiteralFromHsLit x@GHC.HsCharPrim {} =
  Inline $ mkTextValueFromString $ showOutputable x
mkLiteralFromHsLit GHC.HsInt {} = notGeneratedByParser
mkLiteralFromHsLit (GHC.HsIntPrim _ value) =
  Inline $ mkTextValueFromString $ show value ++ "#"
mkLiteralFromHsLit GHC.HsWordPrim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsInt64Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsWord64Prim {} = notGeneratedByParser
#if !MIN_VERSION_ghc_lib_parser(9, 14, 0)
mkLiteralFromHsLit GHC.HsInteger {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsRat {} = notGeneratedByParser
#endif
mkLiteralFromHsLit (GHC.HsFloatPrim _ value) =
  Inline $ mkTextValueFromString $ showOutputable value ++ "#"
mkLiteralFromHsLit GHC.HsDoublePrim {} = notGeneratedByParser
#if MIN_VERSION_ghc_lib_parser(9, 8, 1)
mkLiteralFromHsLit GHC.HsInt8Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsInt16Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsInt32Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsWord8Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsWord16Prim {} = notGeneratedByParser
mkLiteralFromHsLit GHC.HsWord32Prim {} = notGeneratedByParser
#endif
#if MIN_VERSION_ghc_lib_parser(9, 12, 1)
mkLiteralFromHsLit GHC.HsMultilineString {} = notGeneratedByParser
#endif
mkLiteralFromHsLit x =
  case lines $ showOutputable x of
    [] -> Inline $ mkTextValueFromString ""
    [value] -> Inline $ mkTextValueFromString value
    values -> MultilineString $ fmap mkTextValueFromString values

mkLiteralFromHsOverLit :: GHC.HsOverLit GHC.GhcPs -> Literal
#if MIN_VERSION_ghc_lib_parser(9, 8, 1)
mkLiteralFromHsOverLit
  GHC.OverLit
    { GHC.ol_val =
        GHC.HsIntegral GHC.IL {GHC.il_text = GHC.SourceText value}
    } =
    Inline $ mkTextValueFromString $ GHC.unpackFS value
mkLiteralFromHsOverLit
  GHC.OverLit
    { GHC.ol_val =
        GHC.HsIntegral GHC.IL {GHC.il_value = value}
    } =
    Inline $ mkTextValueFromString $ show value
#else
mkLiteralFromHsOverLit
  GHC.OverLit
    { GHC.ol_val =
        GHC.HsIntegral GHC.IL {GHC.il_text = GHC.SourceText value}
    } =
    Inline $ mkTextValueFromString value
mkLiteralFromHsOverLit
  GHC.OverLit
    { GHC.ol_val =
        GHC.HsIntegral GHC.IL {GHC.il_value = value}
    } =
    Inline $ mkTextValueFromString $ show value
#endif
mkLiteralFromHsOverLit GHC.OverLit {GHC.ol_val = GHC.HsFractional fractionalLiteral} =
  Inline $ mkTextValueFromString $ showOutputable fractionalLiteral
mkLiteralFromHsOverLit GHC.OverLit {GHC.ol_val = GHC.HsIsString _ stringValue} =
  Inline $ mkTextValueFromString $ GHC.unpackFS stringValue

mkLiteralFromHsTyLit :: GHC.HsTyLit GHC.GhcPs -> Literal
mkLiteralFromHsTyLit (GHC.HsNumTy _ n) = Inline $ mkTextValueFromString $ show n
mkLiteralFromHsTyLit (GHC.HsStrTy _ s) =
  Inline $ mkTextValueFromText $ Text.pack $ ushow $ GHC.unpackFS s
mkLiteralFromHsTyLit (GHC.HsCharTy _ c) =
  Inline $ mkTextValueFromText $ Text.pack $ ushow c

notGeneratedByParser :: a
notGeneratedByParser =
  error
    "This AST node is not generated by the parser. It only appears in the renaming or type checked stages."
